name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ğŸ“„ Write .env files from secrets
        run: |
          echo "${{ secrets.AUTH_ENV_TEST }}" > apps/auth/.env.test
          echo "${{ secrets.FILES_ENV_TEST }}" > apps/files/.env.test
          echo "${{ secrets.API_GATEWAY_ENV_TEST }}" > apps/api-gateway/.env.test
          echo "${{ secrets.ANTIVIRUS_ENV_TEST }}" > apps/antivirus/.env.test
          echo "${{ secrets.ENV_TEST }}" > .env.test

      - name: ğŸ“¦ Install deps
        run: pnpm install

      - name: ğŸ›  Generate Prisma Clients
        run: |
          pnpm prisma generate --schema=apps/files/src/prisma/schema.prisma
          pnpm prisma generate --schema=apps/auth/src/prisma/schema.prisma

      - name: ğŸ›  Build app
        run: pnpm build

      - name: ğŸ§¼ Lint
        run: pnpm lint

      - name: ğŸ” Typecheck
        run: pnpm typecheck

      - name: âœ… Run tests
        run: pnpm test

      - name: âœ… Run e2e tests
        run: pnpm docker:test-e2e-build

      - name: â¬‡ï¸ Fetch main branch
        run: git fetch origin main

      - name: ğŸ“œ Check commit messages
        run: pnpm commitlint --from=origin/main --to=HEAD